package com.example.newappkotlin_1.data_pojo

data class Rates(
    val AMD: Double,
    val AUD: Double,
    val AZN: Double,
    val BGN: Double,
    val BRL: Double,
    val BYN: Double,
    val CAD: Double,
    val CHF: Double,
    val CNY: Double,
    val CZK: Double,
    val DKK: Double,
    val EUR: Double,
    val GBP: Double,
    val HKD: Double,
    val HUF: Double,
    val INR: Double,
    val JPY: Double,
    val KGS: Double,
    val KRW: Double,
    val KZT: Double,
    val MDL: Double,
    val NOK: Double,
    val PLN: Double,
    val RON: Double,
    val SEK: Double,
    val SGD: Double,
    val TJS: Double,
    val TMT: Double,
    val TRY: Double,
    val UAH: Double,
    val USD: Double,
    val UZS: Double,
    val XDR: Double,
    val ZAR: Double
)